###
GET http://localhost:8080/opai/access-token

###
GET http://localhost:8080/opai/user-info

###
GET http://localhost:8080/opai/user/0121600133841607

###
GET http://localhost:8080/opai/dept-list


###
POST http://localhost:8080/todos/users/h1fjVLMdD6RMnIDOSQXiPzgiEiE/tasks/query
content-type: application/json

{
    "nextToken": null,
    "isDone": false
}


###
POST http://localhost:8080/todos/users/h1fjVLMdD6RMnIDOSQXiPzgiEiE/tasks
content-type: application/json

{
  "creatorId": "h1fjVLMdD6RMnIDOSQXiPzgiEiE",
  "sourceId": null,
  "subject": "todo3",
  "executorIds": ["h1fjVLMdD6RMnIDOSQXiPzgiEiE"]
}